version: '3'

services:
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: on-failure
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql_logs:/var/log/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "200m"
        max-file: "3"

  php:
    build: 
      context: .
      dockerfile: ./images/php/Dockerfile
    container_name: php
    working_dir: /var/www/dices/back
    restart: on-failure
    volumes:
      - .:/var/www/dices/back
    user: "1000:1000"
    env_file: .env
    depends_on:
      - mysql
    ports:
      - 3080:8000
    command: php -S 0.0.0.0:8000 -t /var/www/dices/back
    